# Generated by Django 4.2.2 on 2023-06-13 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_cupon', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('id_status', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='EstadodeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_compra', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormadePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formas_pago', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePais', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSubCategoria', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(default='', max_length=50)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/', validators=[orders.models.validate_image_resolution])),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_categoria', models.ManyToManyField(to='orders.categoria')),
                ('id_subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdendeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cupon_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cupondescuento')),
                ('id_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.descuento')),
                ('id_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.domicilio')),
                ('id_estado_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.estadodecompra')),
                ('id_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.formadepago')),
                ('id_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.producto')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.profile')),
            ],
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.profile'),
        ),
        migrations.CreateModel(
            name='DetalleDescuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.descuento')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.producto')),
            ],
        ),
        migrations.AddField(
            model_name='descuento',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.producto'),
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=50)),
                ('indicativo', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pais')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.departamentos'),
        ),
    ]
